version: "3.8"

services:
  backend:
    build: .
    container_name: go_backend
    ports:
      - "4000:4000"
    environment:
      - GO_ENV=production
      - SWAGGER_HOST=http://localhost:4000
    volumes:
      - ./uploads:/app/uploads
    restart: always
